# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Provide a docker image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BookTest
        path: ./target/*jar
        if-no-files-found: error
        retention-days: 3

  BookTest-Docker-Image: 
      runs-on: ubuntu-latest
      name: Build BookTest-Docker-Image

    steps:
      - name: Checkout the artifact
        uses: actions/checkout@v2

      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: BookTest-Artifact
          path: ./target

      - name: Display artifact
        run:  ls -R
        working-directory: ./target



    # - name: Login to docker hub
    #   uses: actions/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v1


